### ISSUE TITLE
Possibly deprecated files

### ISSUE THREAD

**Issue by ReinderVosDeWael** [cmi-dair/brainviewer#17]
I believe the following files could be removed:

- `/.gitattributes`
- `/index.html`
- `/web-dev-server.config.js`
- `/src/brainviewer/app.ts`

That being said, we may want to consider refactoring the dev-server/index into a GH pages documentation that's also easy to deploy locally. 

Thoughts @nx10 ?

**Comment by nx10** [comment]
Some of them are already gone but feel free to remove the rest
